CREATE TABLE EMPLOYEE (
  EMPLOYEE_ID BIGINT(20) NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  FIRST_NAME varchar(50) NOT NULL,
  LAST_NAME varchar(50) NOT NULL,
  GENDER varchar(10) NOT NULL,
  DOB date
);


CREATE TABLE DEPARTMENT (
  DEPT_ID BIGINT(20) NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 101, INCREMENT BY 1),
  DEPT_CODE varchar(50) NOT NULL,
  DEPT_NAME varchar(50) NOT NULL
);

CREATE TABLE EMPLOYEE_DEPARTMENT (
  ID BIGINT(20) NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  EMPLOYEE_ID BIGINT(10) NOT NULL,
  DEPT_ID BIGINT(10) NOT NULL
);

create sequence hibernate_sequence;




INSERT INTO DEPARTMENT(DEPT_ID, DEPT_CODE, DEPT_NAME) VALUES(101, 'IT', 'Information Technology');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_CODE, DEPT_NAME) VALUES(102, 'HR', 'Human Resource');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_CODE, DEPT_NAME) VALUES(103, 'FINANCE', 'Finance');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_CODE, DEPT_NAME) VALUES(104, 'FACILITY', 'Facility');
INSERT INTO DEPARTMENT(DEPT_ID, DEPT_CODE, DEPT_NAME) VALUES(105, 'OTHER', 'Other');


